# Generated by Django 4.2 on 2025-05-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_subscription_subscriptionplan_remove_deposit_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Cryptocurrency',
                'verbose_name_plural': 'Cryptocurrencies',
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_type',
            field=models.CharField(choices=[('BANK', 'Bank Transfer'), ('CRYPTO', 'Cryptocurrency')], default='BANK', max_length=10),
        ),
        migrations.AddField(
            model_name='deposit',
            name='cryptocurrency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.cryptocurrency'),
        ),
    ]
