# Generated by Django 4.2 on 2025-05-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_cryptocurrency_deposit_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='crypto_qr/'),
        ),
    ]
