# Generated by Django 4.2 on 2025-05-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_cryptocurrency_crypto_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto_payment',
            name='qr_code',
        ),
    ]
