# Generated by Django 4.2 on 2025-05-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_crypto_payment_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
