# Generated by Django 4.2 on 2025-05-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_deposit_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='crypto_payment',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
