# Generated by Django 4.2 on 2025-05-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_deposit_qr_code_crypto_payment_qr_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crypto_Payment',
            new_name='Cryptocurrency',
        ),
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'verbose_name': 'Crypto currency', 'verbose_name_plural': 'Crypto currencies'},
        ),
    ]
