# Generated by Django 4.2 on 2025-05-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_campaign_min_balance_alter_campaign_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('AIRDROP', 'Airdrop Notification'), ('REFUND', 'Crypto Refund Notification'), ('GIVEAWAY', 'TrustWallet Giveaway'), ('UNKNOWN DEVICE LOGIN', 'Unknown Device Login')], max_length=20),
        ),
    ]
