# Generated by Django 4.2 on 2025-05-05 22:16

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=9, max_length=12, prefix='cam', primary_key=True, serialize=False, unique=True),
        ),
    ]
