# Generated by Django 4.2 on 2025-05-05 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cryptocurrency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.cryptocurrency'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='min_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
